version: '2'
services:
  adsleuth:
    build: .
    image: adsleuth:latest
    expose:
      - 8000
    ports:
      - '8000:8000'
    links:
      - postgres
      - elastic
    depends_on:
      - postgres
      - elastic
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=adsleuth
      - POSTGRES_USER=adsleuth
      - POSTGRES_PASSWORD=adsleuth
      - PGDATA=/var/lib/postresql/data/adsleuth
    volumes:
      - './persistent_volumes/postgres_volume:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  elastic:
    image: elasticsearch:latest
    volumes:
      - './persistent_volumes/elasticsearch_volume:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'